/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package episodicv2.Codelets.mpfc;

import episodicv2.core.configuration.Configuration;
import episodicv2.core.entities.Scene;
import episodicv2.core.entities.SceneRelation;
import episodicv2.core.gui.MemoryPanel;
import episodicv2.core.gui.PercentLevelComponent;
import episodicv2.core.t2string.T2DString;
import java.util.ArrayList;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Luis Martin
 */
public class ScenesViewer extends javax.swing.JFrame {

    /**
     * Creates new form ScenesViewer
     */
    private MemoryPanel memoryPanel;

    private static ScenesViewer instance = null;
    private PercentLevelComponent positiveAffectComponent;
    private PercentLevelComponent negativeAffectComponent;

    private ArrayList<Scene> scenes;
    private ConcurrentHashMap<Integer, ArrayList<SceneRelation>> relations;

    private DefaultListModel<Scene> scenesListModel;
    private DefaultListModel relationsListModel;

    public static ScenesViewer getInstance() {

        if (instance == null) {
            instance = new ScenesViewer();
        }

        return instance;
    }

    private ScenesViewer() {
        initComponents();

        memoryPanel = new MemoryPanel(Configuration.GRID_COLUMNS_X, Configuration.GRID_ROWS_Y);
        positiveAffectComponent = new PercentLevelComponent(0.0, true);
        negativeAffectComponent = new PercentLevelComponent(0.0, false);

        scenes = new ArrayList<>();
        relations = new ConcurrentHashMap<>();

        scenesListModel = new DefaultListModel();
        relationsListModel = new DefaultListModel();

        scenesList.setModel(scenesListModel);
        relationsList.setModel(relationsListModel);

        scenesPanel.add(memoryPanel);

        positiveAffectContainer.add(positiveAffectComponent);
        negativeAffectContainer.add(negativeAffectComponent);

        setTitle("Episodic Working Memory");
    }

    public void setItems(ArrayList<Scene> scenes) {

        if (scenes.size() > 0) {
            this.scenes = scenes;

            scenesListModel.clear();

            for (Scene scene : scenes) {
                scenesListModel.addElement(scene);
            }

        }

    }

    public void setPerceivedScene(Scene scene) {

        sceneData.setText(scene.getPattern());

        memoryPanel.setImage(T2DString.decodeMatrix(scene.getPattern(),
                Configuration.GRID_COLUMNS_X,
                Configuration.GRID_ROWS_Y));

        positiveAffectComponent.setPercent(scene.getPositiveAffect());
        negativeAffectComponent.setPercent(scene.getNegativeAffect());
        
        
    }

    public void setRelations(int sceneId, ArrayList<SceneRelation> addRelations) {

        if (sceneId != 0) {
            System.out.println(addRelations.get(0).getScene2Id() + "-");
            relations.put(sceneId, addRelations);
        }
    }

    public void setRelations(ConcurrentHashMap<Integer, ArrayList<SceneRelation>> relations) {

        this.relations = relations;
    }

    public void setImage(ArrayList<Integer>[][] imgM) {
        memoryPanel.setImage(imgM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scenesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        relationsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        scenesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sceneData = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        positiveAffectContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        negativeAffectContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scenesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scenesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(scenesList);

        jLabel1.setText("Scenes");

        jScrollPane2.setViewportView(relationsList);

        jLabel2.setText("Relations");

        scenesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scenesPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        scenesPanel.setLayout(new java.awt.BorderLayout());

        sceneData.setColumns(20);
        sceneData.setRows(5);
        jScrollPane3.setViewportView(sceneData);

        jLabel3.setText("Scene pattern");

        jLabel4.setText("Scene reconstruction");

        positiveAffectContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        positiveAffectContainer.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Affect");

        negativeAffectContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        negativeAffectContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(scenesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(positiveAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(negativeAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scenesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positiveAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negativeAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scenesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scenesListMouseClicked

        try {
            Scene scene = scenesList.getSelectedValue();
            sceneData.setText(scene.toString());

            memoryPanel.setImage(T2DString.decodeMatrix(scene.getPattern(),
                    Configuration.GRID_COLUMNS_X,
                    Configuration.GRID_ROWS_Y));

            positiveAffectComponent.setPercent(scene.getPositiveAffect());
            negativeAffectComponent.setPercent(scene.getNegativeAffect());

            relationsListModel.clear();

            for (SceneRelation sr : relations.get(scene.getId())) {
                relationsListModel.addElement(sr.toString());
            }
        } catch (Exception e) {
            //e.printStackTrace();
            System.out.println("SEGURO LE DISTE CLICK EN EJECUCION");
        }


    }//GEN-LAST:event_scenesListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScenesViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScenesViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScenesViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScenesViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScenesViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel negativeAffectContainer;
    private javax.swing.JPanel positiveAffectContainer;
    private javax.swing.JList<String> relationsList;
    private javax.swing.JTextArea sceneData;
    private javax.swing.JList<Scene> scenesList;
    private javax.swing.JPanel scenesPanel;
    // End of variables declaration//GEN-END:variables
}
