/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package episodicv2.core.gui;

import episodicv2.core.entities.CObject;
import episodicv2.utils.ImageUtils;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author luis_
 */
public class ImageList extends javax.swing.JFrame {

    /**
     * Creates new form ImageList
     */
    private ArrayList<BufferedImage> items;
    private JPanel images;
    private JScrollPane scrollPane;

    private int time = 0;

    private static ImageList instance;

    public static ImageList getInstance() {

        if (instance == null) {
            instance = new ImageList("Objects Working Memory");
        }

        return instance;
    }

    private ImageList(String title) {
        initComponents();

        items = new ArrayList<>();

        images = new JPanel();
        images.setLayout(new GridLayout(3, 3));
        scrollPane = new JScrollPane(images);

        add(scrollPane);

        setTitle(title);
        setSize(400, 400);

    }

    public void setItemImages(ArrayList<BufferedImage> items) {

        images.removeAll();

        for (BufferedImage image : items) {
            ImageComponent imgComp = new ImageComponent(image, 100, 100);
            images.add(imgComp);
        }

        scrollPane.revalidate();
        revalidate();
        pack();
    }

    public void setItems(ArrayList<CObject> items) {

        images.removeAll();
        scrollPane.revalidate();
        revalidate();
        pack();

        for (CObject item : items) {

            BufferedImage image = ImageUtils.getImageFromBase64(item.getFeatures());
            ImageComponent imgComp = new ImageComponent(image, 100, 100);
            images.add(imgComp);
        }

        scrollPane.revalidate();
        revalidate();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
