/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package episodicv2.Codelets.vlpfc;

import episodicv2.core.configuration.Configuration;
import episodicv2.core.entities.ObjectRelations;
import episodicv2.core.gui.ImageComponent;
import episodicv2.core.gui.PercentLevelComponent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;

/**
 *
 * @author Luis Martin
 */
public class RelationsViewer extends javax.swing.JFrame {

    /**
     * Creates new form RelationsViewer
     */
    private static RelationsViewer instance = null;
    private String PATH = Configuration.STORAGE_BASE_PATH + "/itc/features/" + Configuration.ITC_FEATURES_BASEFILENAME;
    private HashMap<Integer, BufferedImage> classFeatures;
    private final int MAX_FEATURES = 81;

    ConcurrentHashMap<Integer, ObjectRelations> relationsMap;
    private DefaultListModel objectListModel;
    private DefaultListModel relationsListModel;

    private ImageComponent object1Img;
    private ImageComponent object2Img;
    private PercentLevelComponent positiveAffectComponent;
    private PercentLevelComponent negativeAffectComponent;
    
    public static RelationsViewer getInstance() {

        if (instance == null) {
            instance = new RelationsViewer();
        }

        return instance;
    }

    private RelationsViewer() {
        initComponents();

        relationsMap = new ConcurrentHashMap<>();

        objectListModel = new DefaultListModel();
        relationsListModel = new DefaultListModel();

        objectList.setModel(objectListModel);
        relationsList.setModel(relationsListModel);

        classFeatures = new HashMap<>();

        object1Img = new ImageComponent();
        object2Img = new ImageComponent();

        object1Panel.add(object1Img);
        object2Panel.add(object2Img);
        positiveAffectComponent = new PercentLevelComponent(0.0, true);
        negativeAffectComponent = new PercentLevelComponent(0.0, false);

        positiveAffectContainer.add(positiveAffectComponent);
        negativeAffectContainer.add(negativeAffectComponent);
        
        loadImages();

        setTitle("Relations Working Memory");
    }

    private void loadImages() {
        try {

            for (int i = 1; i <= MAX_FEATURES; i++) {

                BufferedImage features = ImageIO.read(new File(PATH + "" + i + ".jpg"));

                classFeatures.put(i, features);

            }

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void addRelations(ConcurrentHashMap<Integer, ObjectRelations> relMap) {
        try {

            relationsMap = new ConcurrentHashMap<Integer, ObjectRelations>();
            relationsMap.putAll(relMap);

            objectListModel.clear();
            relationsListModel.clear();

            Iterator<Map.Entry<Integer, ObjectRelations>> it = relationsMap.entrySet().iterator();

            while (it.hasNext()) {
                Map.Entry<Integer, ObjectRelations> item = it.next();

                objectListModel.addElement(item.getKey());

                for (Integer oc : item.getValue().getRelations()) {
                    relationsListModel.addElement(oc);
                }

            }

            /*
            for (Integer objectId : relationsMap.keySet()) {

                objectListModel.addElement(objectId);

                for (Integer oc : relationsMap.get(objectId).getRelations()) {
                    relationsListModel.addElement(oc);
                }

            }*/
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        objectList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        object1Panel = new javax.swing.JPanel();
        object2Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        relationsList = new javax.swing.JList<>();
        positiveAffectContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        negativeAffectContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        objectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                objectListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(objectList);

        jLabel1.setText("Object Relations");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Objects"));

        object1Panel.setPreferredSize(new java.awt.Dimension(128, 128));
        object1Panel.setLayout(new java.awt.BorderLayout());

        object2Panel.setPreferredSize(new java.awt.Dimension(128, 128));
        object2Panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(object1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(object2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(object1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(object2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        relationsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relationsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(relationsList);

        positiveAffectContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        positiveAffectContainer.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Affect");

        negativeAffectContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        negativeAffectContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(positiveAffectContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(negativeAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positiveAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(negativeAffectContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void objectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objectListMouseClicked

        try {
            
            int objectId = objectList.getSelectedValue();

            relationsListModel.clear();

            for (Integer oc : relationsMap.get(objectId).getRelations()) {
                relationsListModel.addElement(oc);
            }

            positiveAffectComponent.setPercent(relationsMap.get(objectId).getPositiveAffect());
            negativeAffectComponent.setPercent(relationsMap.get(objectId).getNegativeAffect());
            
            System.out.println(relationsMap.get(objectId).getPositiveAffect());
            
        } catch (Exception e) {
            System.out.println("Click en ejecución: ");
        }


    }//GEN-LAST:event_objectListMouseClicked

    private void relationsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relationsListMouseClicked

        int objectClass1 = objectList.getSelectedValue();
        int objectClass2 = relationsList.getSelectedValue();

        BufferedImage img1 = classFeatures.get(objectClass1);
        BufferedImage img2 = classFeatures.get(objectClass2);

        object1Img.setImage(img1);
        object2Img.setImage(img2);

    }//GEN-LAST:event_relationsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelationsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelationsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelationsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelationsViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel negativeAffectContainer;
    private javax.swing.JPanel object1Panel;
    private javax.swing.JPanel object2Panel;
    private javax.swing.JList<Integer> objectList;
    private javax.swing.JPanel positiveAffectContainer;
    private javax.swing.JList<Integer> relationsList;
    // End of variables declaration//GEN-END:variables
}
